---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./autobrr/ks.yaml
  - ./bazarr/ks.yaml
  - ./calibre-web/ks.yaml
  - ./changedetection/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./homepage/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./lubelogger/ks.yaml
  - ./plex/ks.yaml
  - ./poenskelisten/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./qui/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./spoolman/ks.yaml
  - ./tautulli/ks.yaml
  - ./tqm/ks.yaml
