---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: authentik-outpost-discovery
  namespace: security
  labels:
    app.kubernetes.io/part-of: authentik
    app.kubernetes.io/component: outpost-controller
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authentik-outpost-discovery
  namespace: security
subjects:
  - kind: ServiceAccount
    name: authentik
    namespace: security
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: authentik-outpost-discovery
