---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./dbinit.yaml
#  - ./helmrelease.yaml
  - ./externalsecret.yaml
#  - ../../../../../shared/templates/gatus/external
  - ../../../../../shared/templates/volsync
